name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: install dependencies
      run: npm i
    - name: run tests
      run: npm run tests
