name: Release

on:
    push:
        branches:
            - master

jobs:
    build:
        env:
            CI: true
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup dependencies
              run: yarn --pure-lockfile

            - name: Setup lerna
              run: yarn setup

            - name: Build packages
              run: yarn build

            - name: Configure CI Git User
              run: |
                  git config --global user.email ds@alfabank.ru
                  git config --global user.name alfa-bot

            - name: Create release
              run: lerna version --conventional-commits --no-commit-hooks --yes --force-git-tag
              env:
                  GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}

            - name: Set NPM Token
              uses: filipstefansson/set-npm-token-action@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Publish
              run: |
                  lerna publish --yes
              env:
                  GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}
