name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 14
    - name: install dependencies
      run: npm i
    - name: bootstrap lerna
      run: npm run setup
    - name: run tests
      run: npm run test
